#!/usr/bin/env bash

# script by enigma158an201
# script available at git repo by cloning: $ git clone https://github.com/enigma158an201/vm-guests-scripts.git

#source "./check-user-privileges"
source "./check-virtual-env"

checkVirtEnv() {
	bFoundString=1 #false
	if command -v virt-what &>/dev/null; then
		sResult="$(suExecCommand virt-what)"
		if [[ ${sResult} =~ "kvm" || ${sResult} =~ "qemu" ]]; then 	bFoundString=0 #true
		else 														bFoundString=1 #false
		fi
	fi
	if [[ -f /etc/os-release ]]; then
		source /etc/os-release
		#if [[ ${NAME,,} =~ linux ]]; then 	bFoundLinux=0; else bFoundLinux=1; fi
		if [[ ${NAME,,} =~ bsd ]]; then 	bFoundBsd=0; else bFoundBsd=1; fi
	fi
	#shellcheck disable=SC2154
	if command -v dmesg &>/dev/null && [[ ${bFoundBsd} -eq 1 ]]; then
		if command -v "${sSuPfx}" &>/dev/null; then 	sResult="$(eval "${sSuPfx} dmesg --notime")"
		else 											sResult="$(dmesg --notime)"; fi
	elif command -v dmesg &>/dev/null && [[ ${bFoundBsd} -eq 0 ]]; then
		if command -v "${sSuPfx}" &>/dev/null; then 	sResult="$(eval "${sSuPfx} dmesg")"
		else											sResult="$(dmesg)" #dmesg --notime ne fonctionne pas avec bsd
		fi
	fi
	sHypervisor=$(grep -i hypervisor <<< "${sResult}" | cut -d ':' -f2 | tr -d " \t\n\r")
	
	if [[ -n ${sHypervisor:-} ]]; then 				bFoundString=0
	else
													for sVirtEnv in virtualbox vboxservice vmware; do
														if [[ ${sResult,,} =~ ${sVirtEnv} ]]; then
																bFoundString=0 #${bFoundString} || echo "true")" #="$(echo  | grep -i )"
														#else 	bFoundString="$(${bFoundString} || echo "false")"
														fi
													done
	fi
	echo "${bFoundString}"
}
