#!/usr/bin/env bash

# script by enigma158an201
set -euo pipefail # -x

# script available at git repo by cloning: $ git clone https://github.com/enigma158an201/vm-guests-scripts.git

checkRootPermissions() {
	if [[ ${UID} = 0 ]] || [[ ${EUID} = 0 ]]; then 	echo "true"
	else 											echo "false"; fi
}
getSuPfx() {
	if [[ "$(checkRootPermissions)" = "false" ]]; then
		if command -v sudo &>/dev/null; then 		echo "sudo"
		elif command -v doas &>/dev/null; then 		echo "doas"
		elif command -v su &>/dev/null; then 		echo "su - -c"
		fi
	else 											echo ""
	fi
}
sSuPfx=$(getSuPfx)
export sSuPfx