#!/usr/bin/env bash
checkRootPermissions() {
	if [[ ${UID} = 0 ]] || [[ ${UID} = 0 ]]; then 	echo "true"
	else 											echo "false"; fi
}
getSuPfx() {
	if [[ "$(checkRootPermissions)" = "false" ]]; then
		if command -v sudo &>/dev/null; then 		echo "sudo"
		elif command -v doas &>/dev/null; then 		echo "doas"
		elif command -v su &>/dev/null; then 		echo "su - -c"
		fi
	else 											echo ""
	fi
}
# shellcheck disable=SC2034
sSuPfx=$(getSuPfx)
export sSuPfx