#!/usr/bin/env bash
checkVirtEnv() {
	bFoundString=1 #false
	#shellcheck disable=SC2154
	if command -v "${sSuPfx}" &>/dev/null; then 	sResult="$(eval "${sSuPfx} dmesg --notime")"
	else 											sResult="$(dmesg --notime)"; fi
	sHypervisor=$(grep -i hypervisor <<< "${sResult}" | cut -d ':' -f2 | tr -d " \t\n\r")
	if [[ -n ${sHypervisor} ]]; then 				bFoundString=0
	else
													for sVirtEnv in virtualbox vboxservice vmware; do
														if [[ ${sResult,,} =~ ${sVirtEnv} ]]; then
																bFoundString=0 #${bFoundString} || echo "true")" #="$(echo  | grep -i )"
														#else 	bFoundString="$(${bFoundString} || echo "false")"
														fi
													done
	fi
	echo "${bFoundString}"
}
