#!/usr/bin/env bash

# script by enigma158an201
# script available at git repo by cloning: $ git clone https://github.com/enigma158an201/vm-guests-scripts.git

updateScriptsViaGit(){
	set +euo pipefail #in case find cannot access some files or folders
	sTargetScript="$(find ~ -nowarn -type f -iname git-pull-refresh.sh 2>/dev/null)" # -exec {} \;
	set -euo pipefail
	if test -f "${sTargetScript}"; then				sGitFolder="$(dirname "${sTargetScript}")"
													cd "${sGitFolder}" || exit 1
													bash "${sTargetScript}" #-x
	fi
}